name: example
description: A new Flutter project.
version: 1.0.1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  provider: ^6.0.3
  # For Dio Kit
  dio: ^5.4.3+1
  flutter_ume: 1.1.4
  flutter_ume_kit_ui: 1.2.1
  flutter_ume_kit_perf: 1.1.1
  flutter_ume_kit_show_code: 1.1.1
  flutter_ume_kit_device: 1.1.1
  flutter_ume_kit_console: 1.2.1
  flutter_ume_kit_dio: 1.2.1
  flutter_ume_kit_channel_monitor: 0.0.3

dependency_overrides:
  vm_service: ^9.4.0
  flutter_ume:
    path: ../

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: ^1.16.6

flutter:
  uses-material-design: true
