name: flutter_ume_kit_channel_monitor
description: channel monitor kit for flutter_ume
version: 0.0.3
homepage: https://github.com/bytedance/flutter_ume

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_ume:
    git:
      url: git@github.com:xbwlai/flutter_ume.git
      ref: flutter_ume-v1.1.4

  rxdart: ^0.27.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=1.0.0 <3.0.0"

flutter:
