name: flutter_ume_kit_perf
description: Performance kits for flutter_ume.
version: 1.1.1
homepage: https://github.com/bytedance/flutter_ume

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_ume:
    git:
      url: git@github.com:xbwlai/flutter_ume.git
      ref: flutter_ume-v1.1.4

  vm_service: ^9.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.12
  flutter_coverage_badge:
    git:
      url: https://github.com/smileShirely/flutter_coverage_badge.git
      ref: 59b7580f406bb712e9d9049c8c99212946e34f65

flutter:
